language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3

notifications:
  email: true

addons:
  code_climate:
    repo_token:
      secure: "Q/S+xsrp+1IgiKs75y6vwlm0L4lSixt9EGKbU5FEKbpgvd558n7WjkWzW03S36Qz8ljk3AZcGXscAkyRaUA3T/IrF84BPIaKwKn+8/pah6mAiKv4La7G0WxW+VO50/1ts9qWLHiRHFyYrqbafdFg6g0q62wRnbfKvL4ezFtGlfI="
