language: ruby
bundler_args: --without development
script: bundle exec rspec spec
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
branches:
  only: master
notifications:
  email: true
